mutation REGISTER_USER {
  registerUser(
    newUser: {
      username: "jdis1111111111"
      email: "asd121111131111@gmail.com"
      password: "1234"
      firstName: "kdb"
      lastName: "asdjhk"
    }
  ) {
    token
    user {
        _id
        username
        email
        lastName
        firstName
    }
  }
}

query AUTHENTICATE_USER($username: String!, $password: String!) {
	authenticateUser(username: $username, password: $password)  {
    token
    user {
      _id
      email
      username
      firstName
      lastName
    }
  }
}

query AUTH_USER {
  authUserProfile{
    _id
    username
    email
    lastName
    firstName
  }
}